export default [
  { code: "AZ", city: "Chandler", shows: 9 },
  { code: "AZ", city: "Phoenix", shows: 5 },
  { code: "AZ", city: "Tempe", shows: 2 },
  { code: "AZ", city: "Tucson", shows: 1 },
  { code: "AL", city: "Birmingham", shows: 4 },
  { code: "AL", city: "Tuscaloosa", shows: 1 },
  { code: "AK", city: "Anchorage", shows: 3 },
  { code: "CA", city: "Anaheim", shows: 4 },
  { code: "CA", city: "Angels Camp", shows: 2 },
  { code: "CA", city: "Atherton", shows: 1 },
  { code: "CA", city: "Bakersfield", shows: 1 },
  { code: "CA", city: "Belmont", shows: 7 },
  { code: "CA", city: "Berkeley", shows: 59 },
  { code: "CA", city: "Carson", shows: 2 },
  { code: "CA", city: "Chico", shows: 1 },
  { code: "CA", city: "Chula Vista", shows: 1 },
  { code: "CA", city: "Compton", shows: 1 },
  { code: "CA", city: "Costa Mesa", shows: 1 },
  { code: "CA", city: "Crockett", shows: 1 },
  { code: "CA", city: "Daly City", shows: 2 },
  { code: "CA", city: "Davis", shows: 3 },
  { code: "CA", city: "Del Mar", shows: 1 },
  { code: "CA", city: "El Monte", shows: 3 },
  { code: "CA", city: "Eureka", shows: 1 },
  { code: "CA", city: "Fresno", shows: 6 },
  { code: "CA", city: "Grass Valley", shows: 1 },
  { code: "CA", city: "Hayward", shows: 1 },
  { code: "CA", city: "Hillsborough", shows: 1 },
  { code: "CA", city: "Inglewood", shows: 7 },
  { code: "CA", city: "Irvine", shows: 15 },
  { code: "CA", city: "Kings Beach", shows: 6 },
  { code: "CA", city: "Long Beach", shows: 13 },
  { code: "CA", city: "Los Angeles", shows: 48 },
  { code: "CA", city: "Marin County", shows: 1 },
  { code: "CA", city: "Menlo Park", shows: 4 },
  { code: "CA", city: "Mill Valley", shows: 1 },
  { code: "CA", city: "Modesto", shows: 1 },
  { code: "CA", city: "Monterey", shows: 3 },
  { code: "CA", city: "Moraga", shows: 1 },
  { code: "CA", city: "Mountain View", shows: 40 },
  { code: "CA", city: "Napa", shows: 3 },
  { code: "CA", city: "Novato", shows: 3 },
  { code: "CA", city: "Oakland", shows: 129 },
  { code: "CA", city: "Palo Alto", shows: 2 },
  { code: "CA", city: "Pasadena", shows: 4 },
  { code: "CA", city: "Pescadero", shows: 2 },
  { code: "CA", city: "Rio Nido", shows: 3 },
  { code: "CA", city: "Rocklin", shows: 1 },
  { code: "CA", city: "Sacramento", shows: 33 },
  { code: "CA", city: "Salinas", shows: 5 },
  { code: "CA", city: "San Bernardino", shows: 5 },
  { code: "CA", city: "San Carlos", shows: 1 },
  { code: "CA", city: "San Diego", shows: 18 },
  { code: "CA", city: "San Francisco", shows: 315 },
  { code: "CA", city: "San Jose", shows: 5 },
  { code: "CA", city: "San Mateo", shows: 3 },
  { code: "CA", city: "San Pedro", shows: 1 },
  { code: "CA", city: "San Quentin", shows: 1 },
  { code: "CA", city: "San Rafael", shows: 12 },
  { code: "CA", city: "Santa Barbara", shows: 5 },
  { code: "CA", city: "Santa Clara", shows: 7 },
  { code: "CA", city: "Santa Cruz", shows: 2 },
  { code: "CA", city: "Santa Monica", shows: 4 },
  { code: "CA", city: "Santa Rosa", shows: 3 },
  { code: "CA", city: "Sausalito", shows: 1 },
  { code: "CA", city: "Soda Springs", shows: 1 },
  { code: "CA", city: "South Lake Tahoe", shows: 1 },
  { code: "CA", city: "Stanford", shows: 16 },
  { code: "CA", city: "Stockton", shows: 2 },
  { code: "CA", city: "Suisun City", shows: 2 },
  { code: "CA", city: "Torrance", shows: 3 },
  { code: "CA", city: "Turlock", shows: 1 },
  { code: "CA", city: "Universal City", shows: 3 },
  { code: "CA", city: "University of California-Santa Barbara", shows: 3 },
  { code: "CA", city: "Ventura", shows: 11 },
  { code: "CA", city: "Walnut Creek", shows: 3 },
  { code: "CA", city: "Watsonville", shows: 1 },
  { code: "CA", city: "West Hollywood", shows: 6 },
  { code: "CO", city: "Boulder", shows: 5 },
  { code: "CO", city: "Colorado Springs", shows: 1 },
  { code: "CO", city: "Denver", shows: 21 },
  { code: "CO", city: "Morrison", shows: 20 },
  { code: "CO", city: "Telluride", shows: 2 },
  { code: "CT", city: "Fairfield", shows: 1 },
  { code: "CT", city: "Hartford", shows: 21 },
  { code: "CT", city: "Middletown", shows: 1 },
  { code: "CT", city: "New Haven", shows: 12 },
  { code: "CT", city: "Waterbury", shows: 2 },
  { code: "FL", city: "Dania Beach", shows: 1 },
  { code: "FL", city: "Gainesville", shows: 1 },
  { code: "FL", city: "Hallandale Beach", shows: 1 },
  { code: "FL", city: "Hollywood", shows: 2 },
  { code: "FL", city: "Homestead", shows: 1 },
  { code: "FL", city: "Jacksonville", shows: 1 },
  { code: "FL", city: "Lakeland", shows: 3 },
  { code: "FL", city: "Miami", shows: 9 },
  { code: "FL", city: "North Miami Beach", shows: 1 },
  { code: "FL", city: "Orlando", shows: 4 },
  { code: "FL", city: "Pembroke Pines", shows: 4 },
  { code: "FL", city: "St. Petersburg", shows: 2 },
  { code: "FL", city: "Sunny Isles Beach", shows: 6 },
  { code: "FL", city: "Tampa", shows: 6 },
  { code: "FL", city: "West Palm Beach", shows: 1 },
  { code: "GA", city: "Atlanta", shows: 36 },
  { code: "HI", city: "Honolulu", shows: 7 },
  { code: "ID", city: "Boise", shows: 1 },
  { code: "IL", city: "Carbondale", shows: 1 },
  { code: "IL", city: "Champaign", shows: 3 },
  { code: "IL", city: "Chicago", shows: 53 },
  { code: "IL", city: "DeKalb", shows: 1 },
  { code: "IL", city: "Edwardsville", shows: 2 },
  { code: "IL", city: "Evanston", shows: 1 },
  { code: "IL", city: "Hoffman Estates", shows: 2 },
  { code: "IL", city: "Normal", shows: 1 },
  { code: "IL", city: "Rosemont", shows: 13 },
  { code: "IL", city: "Tinley Park", shows: 3 },
  { code: "IN", city: "Bloomington", shows: 1 },
  { code: "IN", city: "Indianapolis", shows: 6 },
  { code: "IN", city: "Noblesville", shows: 14 },
  { code: "IN", city: "West Lafayette", shows: 1 },
  { code: "IA", city: "Cedar Falls", shows: 1 },
  { code: "IA", city: "Cedar Rapids", shows: 1 },
  { code: "IA", city: "Des Moines", shows: 4 },
  { code: "IA", city: "Iowa City", shows: 3 },
  { code: "KS", city: "Bonner Springs", shows: 3 },
  { code: "KS", city: "Kansas City", shows: 8 },
  { code: "KS", city: "Wichita", shows: 1 },
  { code: "KY", city: "Lexington", shows: 1 },
  { code: "KY", city: "Louisville", shows: 6 },
  { code: "LA", city: "Baton Rouge", shows: 1 },
  { code: "LA", city: "New Orleans", shows: 7 },
  { code: "LA", city: "Prairieville", shows: 1 },
  { code: "ME", city: "Augusta", shows: 3 },
  { code: "ME", city: "Bangor", shows: 1 },
  { code: "ME", city: "Lewiston", shows: 1 },
  { code: "ME", city: "Orono", shows: 1 },
  { code: "ME", city: "Oxford", shows: 2 },
  { code: "ME", city: "Portland", shows: 8 },
  { code: "MD", city: "Baltimore", shows: 8 },
  { code: "MD", city: "College Park", shows: 1 },
  { code: "MD", city: "Columbia", shows: 6 },
  { code: "MD", city: "Landover", shows: 29 },
  { code: "MA", city: "Amherst", shows: 1 },
  { code: "MA", city: "Billerica", shows: 1 },
  { code: "MA", city: "Boston", shows: 55 },
  { code: "MA", city: "Cambridge", shows: 2 },
  { code: "MA", city: "Foxborough", shows: 3 },
  { code: "MA", city: "South Yarmouth", shows: 2 },
  { code: "MA", city: "Springfield", shows: 10 },
  { code: "MA", city: "Worcester", shows: 14 },
  { code: "MI", city: "Ann Arbor", shows: 6 },
  { code: "MI", city: "Auburn Hills", shows: 8 },
  { code: "MI", city: "Clarkston", shows: 4 },
  { code: "MI", city: "Detroit", shows: 12 },
  { code: "MI", city: "East Lansing", shows: 1 },
  { code: "MI", city: "Grand Rapids", shows: 1 },
  { code: "MN", city: "Bloomington", shows: 4 },
  { code: "MN", city: "Minneapolis", shows: 6 },
  { code: "MN", city: "St. Paul", shows: 6 },
  { code: "MS", city: "Jackson", shows: 1 },
  { code: "MO", city: "Kansas City", shows: 6 },
  { code: "MO", city: "Kirkwood", shows: 1 },
  { code: "MO", city: "Maryland Heights", shows: 4 },
  { code: "MO", city: "St. Louis", shows: 20 },
  { code: "MT", city: "Missoula", shows: 1 },
  { code: "NE", city: "Lincoln", shows: 1 },
  { code: "NE", city: "Omaha", shows: 4 },
  { code: "NV", city: "Las Vegas", shows: 18 },
  { code: "NV", city: "Reno", shows: 2 },
  { code: "NH", city: "Hanover", shows: 1 },
  { code: "NJ", city: "East Rutherford", shows: 30 },
  { code: "NJ", city: "Edison", shows: 1 },
  { code: "NJ", city: "Englishtown", shows: 1 },
  { code: "NJ", city: "Jersey City", shows: 9 },
  { code: "NJ", city: "Passaic", shows: 10 },
  { code: "NJ", city: "Piscataway", shows: 1 },
  { code: "NJ", city: "Princeton", shows: 1 },
  { code: "NJ", city: "Wayne", shows: 1 },
  { code: "NM", city: "Albuquerque", shows: 2 },
  { code: "NM", city: "Santa Fe", shows: 3 },
  { code: "NY", city: "Albany", shows: 13 },
  { code: "NY", city: "Alfred", shows: 1 },
  { code: "NY", city: "Bethel", shows: 1 },
  { code: "NY", city: "Binghamton", shows: 3 },
  { code: "NY", city: "Brooklyn", shows: 4 },
  { code: "NY", city: "Buffalo", shows: 7 },
  { code: "NY", city: "Cortland", shows: 1 },
  { code: "NY", city: "Delhi", shows: 1 },
  { code: "NY", city: "Glens Falls", shows: 4 },
  { code: "NY", city: "Hamilton", shows: 1 },
  { code: "NY", city: "Island Park", shows: 2 },
  { code: "NY", city: "Ithaca", shows: 3 },
  { code: "NY", city: "Lake Placid", shows: 1 },
  { code: "NY", city: "New York", shows: 154 },
  { code: "NY", city: "Niagara Falls", shows: 1 },
  { code: "NY", city: "Orchard Park", shows: 5 },
  { code: "NY", city: "Port Chester", shows: 16 },
  { code: "NY", city: "Queens", shows: 3 },
  { code: "NY", city: "Rochester", shows: 15 },
  { code: "NY", city: "Saratoga Springs", shows: 4 },
  { code: "NY", city: "Stony Brook", shows: 6 },
  { code: "NY", city: "Syracuse", shows: 9 },
  { code: "NY", city: "The Bronx", shows: 1 },
  { code: "NY", city: "Troy", shows: 1 },
  { code: "NY", city: "Uniondale", shows: 42 },
  { code: "NY", city: "Utica", shows: 4 },
  { code: "NY", city: "Vestal", shows: 1 },
  { code: "NY", city: "Watkins Glen", shows: 2 },
  { code: "NC", city: "Chapel Hill", shows: 2 },
  { code: "NC", city: "Charlotte", shows: 12 },
  { code: "NC", city: "Durham", shows: 5 },
  { code: "NC", city: "Greensboro", shows: 7 },
  { code: "NC", city: "Raleigh", shows: 1 },
  { code: "OH", city: "Akron", shows: 1 },
  { code: "OH", city: "Athens", shows: 1 },
  { code: "OH", city: "Cincinnati", shows: 10 },
  { code: "OH", city: "Cleveland", shows: 9 },
  { code: "OH", city: "Columbus", shows: 6 },
  { code: "OH", city: "Cuyahoga Falls", shows: 2 },
  { code: "OH", city: "Dayton", shows: 1 },
  { code: "OH", city: "Richfield", shows: 13 },
  { code: "OH", city: "Thornville", shows: 5 },
  { code: "OK", city: "Norman", shows: 1 },
  { code: "OK", city: "Oklahoma City", shows: 6 },
  { code: "OK", city: "Tulsa", shows: 1 },
  { code: "OR", city: "Ashland", shows: 1 },
  { code: "OR", city: "Corvallis", shows: 2 },
  { code: "OR", city: "Eugene", shows: 22 },
  { code: "OR", city: "Gresham", shows: 3 },
  { code: "OR", city: "Portland", shows: 18 },
  { code: "OR", city: "St. Helens", shows: 1 },
  { code: "OR", city: "Veneta", shows: 2 },
  { code: "PA", city: "Bethlehem", shows: 1 },
  { code: "PA", city: "Burgettstown", shows: 2 },
  { code: "PA", city: "Easton", shows: 1 },
  { code: "PA", city: "Harrisburg", shows: 2 },
  { code: "PA", city: "Hershey", shows: 1 },
  { code: "PA", city: "Lancaster", shows: 1 },
  { code: "PA", city: "Lewisburg", shows: 1 },
  { code: "PA", city: "Meadville", shows: 1 },
  { code: "PA", city: "Philadelphia", shows: 67 },
  { code: "PA", city: "Pittsburgh", shows: 17 },
  { code: "PA", city: "Scranton", shows: 1 },
  { code: "PA", city: "University Park", shows: 2 },
  { code: "PA", city: "Upper Darby", shows: 4 },
  { code: "RI", city: "Providence", shows: 20 },
  { code: "SC", city: "Columbia", shows: 1 },
  { code: "TN", city: "Memphis", shows: 3 },
  { code: "TN", city: "Nashville", shows: 3 },
  { code: "TX", city: "Dallas", shows: 3 },
  { code: "TX", city: "El Paso", shows: 1 },
  { code: "TX", city: "Fort Worth", shows: 2 },
  { code: "TX", city: "Houston", shows: 10 },
  { code: "TX", city: "Manor", shows: 5 },
  { code: "TX", city: "San Antonio", shows: 6 },
  { code: "TX", city: "University Park", shows: 2 },
  { code: "UT", city: "Park City", shows: 2 },
  { code: "UT", city: "Salt Lake City", shows: 7 },
  { code: "VT", city: "Burlington", shows: 2 },
  { code: "VT", city: "Swanton", shows: 2 },
  { code: "VA", city: "Blacksburg", shows: 1 },
  { code: "VA", city: "Charlottesville", shows: 1 },
  { code: "VA", city: "Hampton", shows: 21 },
  { code: "VA", city: "Norfolk", shows: 1 },
  { code: "VA", city: "Richmond", shows: 5 },
  { code: "VA", city: "Roanoke", shows: 3 },
  { code: "VA", city: "Virginia Beach", shows: 1 },
  { code: "VA", city: "Williamsburg", shows: 4 },
  { code: "WA", city: "Seattle", shows: 28 },
  { code: "WA", city: "Spokane", shows: 1 },
  { code: "WA", city: "Sultan", shows: 1 },
  { code: "WA", city: "Tacoma", shows: 1 },
  { code: "WV", city: "Huntington", shows: 1 },
  { code: "WV", city: "Morgantown", shows: 1 },
  { code: "WI", city: "East Troy", shows: 20 },
  { code: "WI", city: "Madison", shows: 7 },
  { code: "WI", city: "Milwaukee", shows: 7 },
  { code: "WI", city: "Poynette", shows: 1 },
];
